TOP_25_SYMBOLS = [

"BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
"ADAUSDT","DOGEUSDT","SUIUSDT","AVAXUSDT","LINKUSDT",
"DOTUSDT","TRXUSDT","LTCUSDT","BCHUSDT","XLMUSDT",
"HBARUSDT","TONUSDT","WLDUSDT","NEARUSDT","APTUSDT",
"ATOMUSDT","ARBUSDT","OPUSDT","ENAUSDT","1000PEPEUSDT",

"SEIUSDT","INJUSDT","FETUSDT","RENDERUSDT","JUPUSDT",
"TAOUSDT","FILUSDT","AAVEUSDT","ALGOUSDT","VETUSDT",
"GRTUSDT","RUNEUSDT","MKRUSDT","ICPUSDT","KASUSDT",
"THETAUSDT","FLOWUSDT","SANDUSDT","MANAUSDT","EGLDUSDT",
"XTZUSDT","AXSUSDT","CHZUSDT","APEUSDT","DYDXUSDT",

"CRVUSDT","UNIUSDT","COMPUSDT","SNXUSDT","1INCHUSDT",
"SUSHIUSDT","ZRXUSDT","LDOUSDT","PENDLEUSDT","GMXUSDT",
"BLURUSDT","ORDIUSDT","ARKMUSDT","WIFUSDT","BONKUSDT",
"FLOKIUSDT","NOTUSDT","PYTHUSDT","STRKUSDT","TIAUSDT",

"ALTUSDT","AIUSDT","AEVOUSDT","PORTALUSDT","ZROUSDT",
"OMUSDT","ONDOUSDT","BRETTUSDT","PEOPLEUSDT","MEMEUSDT",
"SUPERUSDT","IDUSDT","HOOKUSDT","MAGICUSDT","YGGUSDT",

"CFXUSDT","KAVAUSDT","ROSEUSDT","CELOUSDT","MINAUSDT",
"DASHUSDT","ZECUSDT","KSMUSDT","QTUMUSDT","ICXUSDT",

"STXUSDT","NEOUSDT","IOTAUSDT","HOTUSDT","ANKRUSDT",
"OCEANUSDT","BATUSDT","ENSUSDT","BALUSDT","ILVUSDT"
]